# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_v1.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(1129, 698)
        self.savecrop = QtWidgets.QPushButton(Dialog)
        self.savecrop.setGeometry(QtCore.QRect(790, 600, 71, 41))
        self.savecrop.setObjectName("savecrop")
        self.reset = QtWidgets.QPushButton(Dialog)
        self.reset.setGeometry(QtCore.QRect(870, 600, 71, 41))
        self.reset.setObjectName("reset")
        self.textEdit = QtWidgets.QTextEdit(Dialog)
        self.textEdit.setGeometry(QtCore.QRect(270, 590, 491, 71))
        self.textEdit.setObjectName("textEdit")
        self.textBrowser = QtWidgets.QTextBrowser(Dialog)
        self.textBrowser.setGeometry(QtCore.QRect(20, 30, 381, 31))
        self.textBrowser.setObjectName("textBrowser")
        self.textBrowser_2 = QtWidgets.QTextBrowser(Dialog)
        self.textBrowser_2.setGeometry(QtCore.QRect(570, 30, 381, 31))
        self.textBrowser_2.setObjectName("textBrowser_2")
        self.openfile_1 = QtWidgets.QPushButton(Dialog)
        self.openfile_1.setGeometry(QtCore.QRect(410, 30, 81, 31))
        self.openfile_1.setObjectName("openfile_1")
        self.openfile_2 = QtWidgets.QPushButton(Dialog)
        self.openfile_2.setGeometry(QtCore.QRect(960, 30, 81, 31))
        self.openfile_2.setObjectName("openfile_2")
        self.splitter = QtWidgets.QSplitter(Dialog)
        self.splitter.setGeometry(QtCore.QRect(20, 130, 1081, 411))
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName("splitter")
        self.graphicsView_3 = QtWidgets.QGraphicsView(self.splitter)
        self.graphicsView_3.setObjectName("graphicsView_3")
        self.graphicsView_4 = QtWidgets.QGraphicsView(self.splitter)
        self.graphicsView_4.setObjectName("graphicsView_4")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.savecrop.setText(_translate("Dialog", "cropsave"))
        self.reset.setText(_translate("Dialog", "reset"))
        self.openfile_1.setText(_translate("Dialog", "openfile"))
        self.openfile_2.setText(_translate("Dialog", "openfile"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
